### ISSUE TITLE
[Feature]: Adding loader with an App logo

### ISSUE THREAD

**Issue by Vidip-Ghosh** [Vidip-Ghosh/CertVault#17]
<img width="241" alt="Screenshot 2023-10-06 at 20 15 48" src="https://github.com/Vidip-Ghosh/CertVault/assets/91741581/926a5ca2-2ac7-4c7a-83cb-b262aa5678a4">

Like this. After this loader login page should appear.

**Comment by Thilagavathi1** [comment]
Hi @Vidip-Ghosh Could u please assign this issue to me.i am interested to work on this issues

**Comment by Vidip-Ghosh** [comment]
> Hi @Vidip-Ghosh Could u please assign this issue to me.i am interested to work on this issues

Yes sure. Go for it.

**Comment by Thilagavathi1** [comment]
@Vidip-Ghosh Raised an [PR ](https://github.com/Vidip-Ghosh/CertVault/pull/18), please review it and let me know the feedback.

**Comment by Vidip-Ghosh** [comment]
> @Vidip-Ghosh Raised an [PR ](https://github.com/Vidip-Ghosh/CertVault/pull/18), please review it and let me know the feedback.

Great work
