### ISSUE TITLE
[BUG]: Login & SignUp Functionality

### ISSUE THREAD

**Issue by arcVaishali** [Vidip-Ghosh/CertVault#6]
Whenever a user tries to signup using his credentials and clicks on **SignUp**, its not able to redirect him/her towards dashboard. More precisely a ```log undefined``` error logs in the terminal each time user tries signing up.

**Comment by Dineshraju3435** [comment]
hey , This is dinesh and  I am new for open source, what exactly is the bug like what should we do for the above question?

**Comment by Vidip-Ghosh** [comment]
https://github.com/Vidip-Ghosh/CertVault/assets/91741581/b1d272b9-be5b-47f5-a327-fdf40c4bf09d

See @Dineshraju3435 actually, when we click on signup, it should redirect to dashboard. 
But its not working as expected & throwing undefined in console.

**Comment by Thehackerash** [comment]
please assign this issue to me

**Comment by Vidip-Ghosh** [comment]
@Dineshraju3435 Would you like to work? If yes, please let me know. 
Or 
can I assign this issue @Thehackerash ?

**Comment by Thehackerash** [comment]
I will try my bestt...

**Comment by Vidip-Ghosh** [comment]
@Thehackerash go for it. 
All the best.

**Comment by p7uverma** [comment]
I fixed it

**Comment by Vidip-Ghosh** [comment]
@Thehackerash  apologize to state that the issue is already been solved by @p7uverma 
But @Thehackerash you can still contribute & if you get any issue OR want to add feature. Please feel free to create issue & get assigned.
