### ISSUE TITLE
feature: cert upload functionality

### ISSUE THREAD

**Issue by Gobinath-B** [Vidip-Ghosh/CertVault#8]
### Description
. upload functionality to upload certificate and store it on mongodb

**Comment by Vidip-Ghosh** [comment]
Actually, one of the contributor is working on to fix Login/SignUp functionality. 
As soon as it gets fixed, I'll assign you this issue.

**Comment by Vidip-Ghosh** [comment]
Hey, you can start working now. 
The issue of login/signup has been fixed & make sure you synchronize your forked branch and start working in order to avoid getting merge conflicts.

**Comment by Vidip-Ghosh** [comment]
@Gobinath-B create different branches for both the issues. 
Go for it.

**Comment by Vidip-Ghosh** [comment]
Hey @Gobinath-B are you working on this issue?

**Comment by Gobinath-B** [comment]
@Vidip-Ghosh yup I'm working on this feature. can you please label this as feature

**Comment by Gobinath-B** [comment]
@Vidip-Ghosh  I can't login or signup

**Comment by Vidip-Ghosh** [comment]
Create a .env file in server & place the value of URL. 
https://www.mongodb.com/  -> Create a free cluster from this site and place it in .env file.

**Comment by Vidip-Ghosh** [comment]
Are you able to sign up @Gobinath-B ?
